<?php

namespace Cypher\Compiler\CodeGen;

use Cypher\Compiler\Project\AppProject;

trait AutoGeneratedTrait
{
    private ?AppProject $project = null;

    public function autoGeneratedNote(string $type = '//'): string
    {
        $projectName = $this->project?->getConfig()->get('name', 'cyp-project') ?? 'cyp-project';
        $lines = [
            "{$type} ============================================================",
            "{$type} AUTO-GENERATED by CYP Compiler — DO NOT EDIT",
            "{$type} Source of truth: .cyp files in the project directory",
            "{$type} Project: {$projectName}",
            "{$type} Generated: " . date('Y-m-d H:i:s'),
            "{$type} To update: Edit the corresponding .cyp file and recompile",
            "{$type} ============================================================",
            '',
        ];
        return implode("\n", $lines);
    }

    public function setProject(?AppProject $project): void
    {
        $this->project = $project;
    }
}
