<?php

namespace Cypher\Compiler\SourceGenerator;

use Cypher\Compiler\Project\AppProject;
use Cypher\Compiler\AST\{
    ModuleNode, VarDeclStmt, SayStmt, AssignStmt, IfStmt, ForStmt,
    RepeatStmt, ReturnStmt, TryCatchStmt, ThrowStmt,
    ModelDeclStmt, PageDeclStmt, ApiDeclStmt, ComponentDeclStmt,
    TaskDeclStmt, AgentDeclStmt, ParamDecl, ModelField, ModelRelationship,
    LiteralExpr, IdentifierExpr, BinaryExpr, CallExpr,
    ArrayExpr, RecordExpr, FieldExpr,
};

class SourceGenerator
{
    public const TEMPLATES_DIR = 'templates';

    private array $generated = [];
    private string $projectRoot;

    public function __construct(string $projectRoot)
    {
        $this->projectRoot = rtrim($projectRoot, DIRECTORY_SEPARATOR);
    }

    public static function fromDescription(string $name, string $description): array
    {
        $interpreter = new ApplicationInterpreter();
        return $interpreter->interpret($name, $description);
    }

    public function generateModel(string $name, array $fields = [], array $relationships = []): string
    {
        $code = "# {$name} model\n";
        $code .= "# Generated by CYP Source Generator\n\n";
        $code .= "model {$name}\n";
        foreach ($fields as $field) {
            $attrs = '';
            if (!empty($field['attributes'])) {
                $attrs = ' ' . implode(' ', $field['attributes']);
            }
            $code .= "    {$field['name']}: {$field['type']}{$attrs}\n";
        }
        foreach ($relationships as $rel) {
            $code .= "    {$rel['name']} {$rel['type']} {$rel['target']}\n";
        }
        $code .= "end\n";
        return $code;
    }

    public function generatePage(string $name, array $content = [], array $options = []): string
    {
        $code = "# {$name} page\n";
        $code .= "# Generated by CYP Source Generator\n\n";
        $code .= "page {$name}\n";
        foreach ($content as $line) {
            if ($line['type'] === 'say') {
                $code .= "    say \"{$line['value']}\"\n";
            } elseif ($line['type'] === 'var') {
                $code .= "    {$line['name']} = \"{$line['value']}\"\n";
            } elseif ($line['type'] === 'for') {
                $code .= "    for {$line['variable']} in {$line['iterable']}\n";
                foreach ($line['body'] as $bodyLine) {
                    $code .= "        {$bodyLine}\n";
                }
                $code .= "    end\n";
            }
        }
        $code .= "end\n";
        return $code;
    }

    public function generateApi(string $method, string $path, array $body = []): string
    {
        $code = "# API endpoint: {$method} {$path}\n";
        $code .= "# Generated by CYP Source Generator\n\n";
        $code .= "api {$method} \"{$path}\"\n";
        foreach ($body as $stmt) {
            if ($stmt['type'] === 'return') {
                $code .= "    return {$stmt['value']}\n";
            } elseif ($stmt['type'] === 'say') {
                $code .= "    say \"{$stmt['value']}\"\n";
            } elseif ($stmt['type'] === 'assign') {
                $code .= "    {$stmt['name']} = {$stmt['value']}\n";
            }
        }
        if (empty($body)) {
            $code .= "    return ['status' => 'ok', 'method' => '{$method}', 'path' => '{$path}']\n";
        }
        $code .= "end\n";
        return $code;
    }

    public function generateAgent(string $name, string $model = 'gpt4', array $tasks = [], ?string $prompt = null): string
    {
        $code = "# {$name} AI Agent\n";
        $code .= "# Generated by CYP Source Generator\n\n";
        $code .= "agent {$name}: {$model}\n";
        if ($prompt) {
            $code .= "    prompt \"{$prompt}\"\n";
        }
        foreach ($tasks as $task) {
            $code .= "\n    task {$task['name']}({$task['params']})\n";
            foreach ($task['body'] as $line) {
                $code .= "        {$line}\n";
            }
            $code .= "    end\n";
        }
        $code .= "end\n";
        return $code;
    }

    public function generateWorkflow(string $name, array $steps = []): string
    {
        $code = "# {$name} workflow\n";
        $code .= "# Generated by CYP Source Generator\n";
        $code .= "# Workflow consists of tasks that can be chained together\n\n";
        foreach ($steps as $i => $step) {
            $safeName = preg_replace('/[^a-zA-Z0-9]/', '', $step['name']);
            $code .= "task {$name}Step{$i}_{$safeName}()\n";
            foreach ($step['body'] as $line) {
                $code .= "    {$line}\n";
            }
            $code .= "end\n\n";
        }
        $code .= "# Workflow: {$name}\n";
        $code .= "# Steps: " . implode(' → ', array_column($steps, 'name')) . "\n";
        return $code;
    }

    public function generateComponent(string $name, array $props = [], array $content = []): string
    {
        $propStr = !empty($props) ? '(' . implode(', ', $props) . ')' : '';
        $code = "# {$name} UI component\n";
        $code .= "# Generated by CYP Source Generator\n\n";
        $code .= "component {$name}{$propStr}\n";
        foreach ($content as $line) {
            if ($line['type'] === 'say') {
                $code .= "    say \"{$line['value']}\"\n";
            }
        }
        $code .= "end\n";
        return $code;
    }

    public function generateAppStub(string $name): string
    {
        return "# {$name} — CYP Application\n" .
               "# Generated by CYP Source Generator\n\n" .
               "name = \"{$name}\"\n" .
               "say \"Hello from {name}!\"\n";
    }

    public function writeToProject(array $files, ?AppProject $project = null): array
    {
        $root = $project ? $project->getRootPath() : $this->projectRoot;
        $written = [];

        foreach ($files as $relativePath => $content) {
            $fullPath = $root . DIRECTORY_SEPARATOR . $relativePath;
            $dir = dirname($fullPath);
            if (!is_dir($dir)) {
                mkdir($dir, 0777, true);
            }
            file_put_contents($fullPath, $content);
            $written[] = $relativePath;
        }

        return $written;
    }

    public function generateFullApp(string $name, array $spec): array
    {
        $files = [];

        $files['app.cyp'] = $this->generateAppStub($name);

        foreach ($spec['models'] ?? [] as $model) {
            $path = "models/" . strtolower($model['name']) . ".cyp";
            $files[$path] = $this->generateModel($model['name'], $model['fields'] ?? [], $model['relationships'] ?? []);
        }

        foreach ($spec['pages'] ?? [] as $page) {
            $path = "pages/" . strtolower($page['name']) . ".cyp";
            $files[$path] = $this->generatePage($page['name'], $page['content'] ?? [], $page['options'] ?? []);
        }

        foreach ($spec['apis'] ?? [] as $api) {
            $cleanPath = trim(str_replace(['/', '{', '}', '-'], '_', ltrim($api['path'], '/')));
            $path = "api/" . $cleanPath . ".cyp";
            $files[$path] = $this->generateApi($api['method'], $api['path'], $api['body'] ?? []);
        }

        foreach ($spec['agents'] ?? [] as $agent) {
            $path = "agents/" . strtolower($agent['name']) . ".cyp";
            $files[$path] = $this->generateAgent($agent['name'], $agent['model'] ?? 'gpt4', $agent['tasks'] ?? [], $agent['prompt'] ?? null);
        }

        foreach ($spec['workflows'] ?? [] as $workflow) {
            $path = "workflows/" . strtolower($workflow['name']) . ".cyp";
            $files[$path] = $this->generateWorkflow($workflow['name'], $workflow['steps'] ?? []);
        }

        foreach ($spec['components'] ?? [] as $component) {
            $path = "components/" . strtolower($component['name']) . ".cyp";
            $files[$path] = $this->generateComponent($component['name'], $component['props'] ?? [], $component['content'] ?? []);
        }

        return $files;
    }

    public function generateFromAst(ModuleNode $ast): array
    {
        $files = [];

        foreach ($ast->statements as $stmt) {
            $code = match ($stmt::class) {
                ModelDeclStmt::class => $this->modelToCyp($stmt),
                PageDeclStmt::class => $this->pageToCyp($stmt),
                ApiDeclStmt::class => $this->apiToCyp($stmt),
                TaskDeclStmt::class => $this->taskToCyp($stmt),
                AgentDeclStmt::class => $this->agentToCyp($stmt),
                ComponentDeclStmt::class => $this->componentToCyp($stmt),
                default => null,
            };

            if ($code !== null) {
                $name = $stmt->name ?? $stmt->path ?? 'unnamed';
                $category = $this->categoryFor($stmt);
                $filename = strtolower(preg_replace('/[^a-z0-9]/i', '_', $name)) . '.cyp';
                $files["{$category}/{$filename}"] = $code;
            }
        }

        return $files;
    }

    public function modelToCyp(ModelDeclStmt $stmt): string
    {
        $code = "model {$stmt->name}\n";
        foreach ($stmt->fields as $field) {
            $attrs = '';
            if (!empty($field->attributes)) {
                $attrs = ' ' . implode(' ', $field->attributes);
            }
            $code .= "    {$field->name}: {$field->type}{$attrs}\n";
        }
        foreach ($stmt->relationships as $rel) {
            $code .= "    {$rel->name} {$rel->type} {$rel->target}\n";
        }
        $code .= "end\n";
        return $code;
    }

    public function taskToCyp(TaskDeclStmt $stmt): string
    {
        $params = implode(', ', array_map(fn($p) => $p->typeHint ? "{$p->name}: {$p->typeHint}" : $p->name, $stmt->params));
        $retType = $stmt->returnType ? ": {$stmt->returnType}" : '';
        $code = "task {$stmt->name}({$params}){$retType}\n";
        $code .= "    # Task body omitted for generation\n";
        $code .= "end\n";
        return $code;
    }

    public function pageToCyp(PageDeclStmt $stmt): string
    {
        $code = "page {$stmt->name}\n";
        foreach ($stmt->body as $s) {
            $code .= $this->stmtToCyp($s, 1);
        }
        $code .= "end\n";
        return $code;
    }

    public function apiToCyp(ApiDeclStmt $stmt): string
    {
        $code = "api {$stmt->method} \"{$stmt->path}\"\n";
        foreach ($stmt->body as $s) {
            $code .= $this->stmtToCyp($s, 1);
        }
        $code .= "end\n";
        return $code;
    }

    public function agentToCyp(AgentDeclStmt $stmt): string
    {
        $code = "agent {$stmt->name}: {$stmt->model}\n";
        if ($stmt->systemPrompt) {
            $code .= "    prompt \"{$stmt->systemPrompt}\"\n";
        }
        foreach ($stmt->body as $s) {
            $code .= $this->stmtToCyp($s, 1);
        }
        $code .= "end\n";
        return $code;
    }

    public function componentToCyp(ComponentDeclStmt $stmt): string
    {
        $props = implode(', ', array_map(fn($p) => $p->typeHint ? "{$p->name}: {$p->typeHint}" : $p->name, $stmt->props));
        $code = "component {$stmt->name}($props)\n";
        foreach ($stmt->body as $s) {
            $code .= $this->stmtToCyp($s, 1);
        }
        $code .= "end\n";
        return $code;
    }

    private function stmtToCyp($stmt, int $indent = 0): string
    {
        $pad = str_repeat('    ', $indent);

        return match ($stmt::class) {
            VarDeclStmt::class => $pad . "{$stmt->name} = {$this->exprToCyp($stmt->initializer)}\n",
            SayStmt::class => $pad . "say \"{$this->exprToString($stmt->expression)}\"\n",
            AssignStmt::class => $pad . "{$this->exprToCyp($stmt->target)} = {$this->exprToCyp($stmt->value)}\n",
            ReturnStmt::class => $pad . ($stmt->value ? "return {$this->exprToCyp($stmt->value)}\n" : "return\n"),
            default => '',
        };
    }

    private function exprToCyp($expr): string
    {
        return match ($expr::class) {
            LiteralExpr::class => $expr->literalType === 'string' ? "\"{$expr->value}\"" : (string)$expr->value,
            IdentifierExpr::class => $expr->name,
            CallExpr::class => $this->exprToCyp($expr->callee) . '(' . implode(', ', array_map(fn($a) => $this->exprToCyp($a), $expr->arguments)) . ')',
            PropertyAccessExpr::class => $this->exprToCyp($expr->object) . '.' . $expr->property,
            default => '/* expr */',
        };
    }

    private function exprToString($expr): string
    {
        if ($expr instanceof LiteralExpr && $expr->literalType === 'string') {
            return $expr->value;
        }
        return '{expression}';
    }

    private function categoryFor($stmt): string
    {
        return match ($stmt::class) {
            ModelDeclStmt::class => 'models',
            PageDeclStmt::class => 'pages',
            ApiDeclStmt::class => 'api',
            TaskDeclStmt::class => 'tasks',
            AgentDeclStmt::class => 'agents',
            ComponentDeclStmt::class => 'components',
            default => '.',
        };
    }
}
