<?php

namespace Cypher\Compiler\CodeGen\Database;

use Cypher\Compiler\AST\{
    ModuleNode, ModelDeclStmt, ModelField, ModelRelationship,
};
use Cypher\Compiler\CodeGen\AutoGeneratedTrait;

class PostgresGenerator
{
    use AutoGeneratedTrait;

    private array $generatedFiles = [];
    private array $config;

    public function __construct(array $config = [], ?\Cypher\Compiler\Project\AppProject $project = null)
    {
        $this->config = $config;
        $this->project = $project;
    }

    public function generate(ModuleNode $module): array
    {
        $this->generatedFiles = [];

        $this->generatedFiles['database/schema.sql'] = $this->generateSchemaHeader();

        foreach ($module->statements as $stmt) {
            if ($stmt instanceof ModelDeclStmt) {
                $this->generateModelSQL($stmt);
            }
        }

        $this->generatedFiles['database/seed.sql'] = $this->autoGeneratedNote('--') . "\n-- Database seed data will be inserted here\n";

        return $this->generatedFiles;
    }

    private function generateSchemaHeader(): string
    {
        return $this->autoGeneratedNote('--') . <<<SQL

-- CYP Generated PostgreSQL Schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

SQL;
    }

    private function generateModelSQL(ModelDeclStmt $stmt): void
    {
        $table = $this->tableName($stmt->name);
        $columns = [];
        $indexes = [];
        $foreignKeys = [];

        $columns[] = '    id UUID PRIMARY KEY DEFAULT uuid_generate_v4()';

        foreach ($stmt->fields as $field) {
            $colDef = $this->columnDefinition($field);
            if ($colDef) {
                $columns[] = $colDef;
            }
            if (in_array('unique', $field->attributes)) {
                $indexes[] = "CREATE UNIQUE INDEX idx_{$table}_{$field->name} ON {$table}({$field->name});";
            }
        }

        foreach ($stmt->relationships as $rel) {
            $fkCol = $rel->foreignKey;
            $targetTable = $this->tableName($rel->target);
            $columns[] = "    {$fkCol} UUID NOT NULL";
            $foreignKeys[] = "    FOREIGN KEY ({$fkCol}) REFERENCES {$targetTable}(id) ON DELETE CASCADE";
            $indexes[] = "CREATE INDEX idx_{$table}_{$fkCol} ON {$table}({$fkCol});";
        }

        $columns[] = '    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()';
        $columns[] = '    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()';

        $hasVector = false;
        foreach ($stmt->fields as $f) {
            if (strtolower($f->type) === 'vector') { $hasVector = true; break; }
        }
        $enableVector = $hasVector
            ? "-- Requires pgvector extension\n-- CREATE EXTENSION IF NOT EXISTS vector;\n\n"
            : '';

        $sql = $enableVector;
        $sql .= "CREATE TABLE IF NOT EXISTS {$table} (\n";
        $sql .= implode(",\n", $columns);
        if (!empty($foreignKeys)) {
            $sql .= ",\n" . implode(",\n", $foreignKeys);
        }
        $sql .= "\n);\n\n";

        $sql .= "COMMENT ON TABLE {$table} IS '{$stmt->name} model generated by CYP';\n\n";

        foreach ($indexes as $idx) {
            $sql .= $idx . "\n";
        }
        $sql .= "\n";

        $this->generatedFiles['database/schema.sql'] .= $sql;

        $timestamp = date('Ymd_His');
        $this->generatedFiles["database/migrations/{$timestamp}_create_{$table}_table.sql"] = $sql;
    }

    private function columnDefinition(ModelField $field): ?string
    {
        $pgType = $this->pgType($field->type);
        $nullable = in_array('nullable', $field->attributes) ? '' : ' NOT NULL';
        $unique = in_array('unique', $field->attributes) ? ' UNIQUE' : '';
        $default = '';

        if (in_array('default', $field->attributes)) {
            $default = " DEFAULT '{$field->name}_default'";
        }

        return "    {$field->name} {$pgType}{$nullable}{$unique}{$default}";
    }

    private function pgType(string $type): string
    {
        return match (strtolower($type)) {
            'int', 'integer', 'bigint' => 'BIGINT',
            'string', 'varchar' => 'VARCHAR(255)',
            'text' => 'TEXT',
            'float', 'double', 'decimal' => 'DOUBLE PRECISION',
            'bool', 'boolean' => 'BOOLEAN',
            'datetime', 'timestamp' => 'TIMESTAMP WITH TIME ZONE',
            'date' => 'DATE',
            'json' => 'JSONB',
            'uuid' => 'UUID',
            'vector' => 'vector(1536)',
            'email' => 'VARCHAR(255)',
            'password' => 'VARCHAR(255)',
            default => 'VARCHAR(255)',
        };
    }

    private function tableName(string $name): string
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $name)) . 's';
    }
}
